[package]
name = "bluebeam_crypto"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
x25519-dalek = "2.0"
sha2 = "0.10"
rand = "0.8"
base64 = "0.21"
thiserror = "1.0"
aes-gcm = "0.10"

[lints.clippy]
security = "warn"
pedantic = "warn"
nursery = "warn"